import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./components/navigation";

const plein = localFont({
  src: "../fonts/Plein-Variable.ttf",
  variable: "--font-plein",
});

const archivo = localFont({
  src: "../fonts/Archivo-Variable.ttf",
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plein.variable} ${archivo.variable} antialiased`}>
        {children}
        <Navigation />
      </body>
    </html>
  );
}
